# file: core/reporter.py
import json
import csv
import os
from datetime import datetime
from pathlib import Path

class Reporter:
    """রিপোর্ট জেনারেটর"""
    
    def __init__(self):
        self.report_dir = "reports"
        self.ensure_directory()
    
    def ensure_directory(self):
        """রিপোর্ট ডিরেক্টরি নিশ্চিত করুন"""
        if not os.path.exists(self.report_dir):
            os.makedirs(self.report_dir)
    
    def generate_json_report(self, data, filename=None):
        """JSON রিপোর্ট তৈরি"""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.json"
        
        filepath = os.path.join(self.report_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        
        print(f" JSON report saved: {filepath}")
        return filepath
    
    def generate_html_report(self, data, filename=None):
        """HTML রিপোর্ট তৈরি"""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.html"
        
        filepath = os.path.join(self.report_dir, filename)
        
        html_template = self.create_html_template(data)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_template)
        
        print(f" HTML report saved: {filepath}")
        return filepath
    
    def create_html_template(self, data):
        """HTML টেম্পলেট তৈরি"""
        html = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MAR-PD Scan Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f5f5f5;
        }}
        .container {{
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }}
        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 10px;
            margin-bottom: 20px;
        }}
        .section {{
            margin-bottom: 30px;
            padding: 20px;
            background: #f9f9f9;
            border-radius: 8px;
            border-left: 4px solid #667eea;
        }}
        .data-table {{
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }}
        .data-table th, .data-table td {{
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
        }}
        .data-table th {{
            background-color: #667eea;
            color: white;
        }}
        .data-table tr:nth-child(even) {{
            background-color: #f2f2f2;
        }}
        .success {{
            color: #28a745;
            font-weight: bold;
        }}
        .error {{
            color: #dc3545;
            font-weight: bold;
        }}
        .warning {{
            color: #ffc107;
            font-weight: bold;
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1> MAR-PD Scan Report</h1>
            <p>Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </div>
        
        <div class="section">
            <h2> Summary</h2>
            <div id="summary">
                {self.generate_summary_html(data)}
            </div>
        </div>
        
        <div class="section">
            <h2> Scan Results</h2>
            <div id="results">
                {self.generate_results_html(data)}
            </div>
        </div>
        
        <div class="section">
            <h2>⚠️ Security Notes</h2>
            <div id="security">
                {self.generate_security_html()}
            </div>
        </div>
        
        <div class="section">
            <h2> Footer</h2>
            <p>This report was generated by MAR-PD v3.0</p>
            <p><strong>Remember:</strong> Use this information ethically and legally.</p>
        </div>
    </div>
    
    <script>
        // Simple JavaScript for interactivity
        document.addEventListener('DOMContentLoaded', function() {{
            // Add click handlers to tables
            const tables = document.querySelectorAll('.data-table');
            tables.forEach(table => {{
                table.addEventListener('click', function(e) {{
                    if (e.target.tagName === 'TD') {{
                        e.target.parentElement.classList.toggle('highlight');
                    }}
                }});
            }});
        }});
    </script>
</body>
</html>
"""
        return html
    
    def generate_summary_html(self, data):
        """সারাংশ HTML জেনারেট"""
        if isinstance(data, dict) and 'summary' in data:
            summary = data['summary']
            html = f"""
            <table class="data-table">
                <tr>
                    <th>Metric</th>
                    <th>Value</th>
                </tr>
                <tr>
                    <td>Total Methods Run</td>
                    <td>{summary.get('total_methods_run', 0)}</td>
                </tr>
                <tr>
                    <td>Successful Methods</td>
                    <td class="success">{summary.get('successful_methods', 0)}</td>
                </tr>
                <tr>
                    <td>Unique Emails Found</td>
                    <td>{summary.get('unique_emails', 0)}</td>
                </tr>
                <tr>
                    <td>Unique Phones Found</td>
                    <td>{summary.get('unique_phones', 0)}</td>
                </tr>
            </table>
            """
            return html
        return "<p>No summary data available.</p>"
    
    def generate_results_html(self, data):
        """রেজাল্টস HTML জেনারেট"""
        if isinstance(data, dict) and 'results' in data:
            results = data['results']
            html = ""
            
            for method, result in results.items():
                html += f"""
                <div style="margin-bottom: 15px;">
                    <h3>{method}</h3>
                    <pre style="background: #f0f0f0; padding: 10px; border-radius: 5px; overflow-x: auto;">
{json.dumps(result, indent=2)}
                    </pre>
                </div>
                """
            
            return html
        
        return "<p>No results data available.</p>"
    
    def generate_security_html(self):
        """সিকিউরিটি HTML জেনারেট"""
        return """
        <div class="warning">
            <p><strong>⚠️ Important Security Notes:</strong></p>
            <ul>
                <li>This report may contain sensitive information</li>
                <li>Store this report securely</li>
                <li>Do not share with unauthorized persons</li>
                <li>Use information only for ethical purposes</li>
                <li>Respect privacy and follow applicable laws</li>
            </ul>
        </div>
        """
    
    def generate_csv_report(self, data, filename=None):
        """CSV রিপোর্ট তৈরি"""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"report_{timestamp}.csv"
        
        filepath = os.path.join(self.report_dir, filename)
        
        # Flatten data for CSV
        flat_data = self.flatten_for_csv(data)
        
        with open(filepath, 'w', newline='', encoding='utf-8') as f:
            if flat_data:
                writer = csv.DictWriter(f, fieldnames=flat_data[0].keys())
                writer.writeheader()
                writer.writerows(flat_data)
        
        print(f" CSV report saved: {filepath}")
        return filepath
    
    def flatten_for_csv(self, data, parent_key='', sep='_'):
        """CSV এর জন্য ডাটা flatten করা"""
        items = []
        
        if isinstance(data, dict):
            for k, v in data.items():
                new_key = f"{parent_key}{sep}{k}" if parent_key else k
                if isinstance(v, dict):
                    items.extend(self.flatten_for_csv(v, new_key, sep))
                elif isinstance(v, list):
                    # লিস্ট হলে স্ট্রিং হিসেবে সেভ
                    items.append({new_key: str(v)})
                else:
                    items.append({new_key: v})
        elif isinstance(data, list):
            for i, item in enumerate(data):
                items.extend(self.flatten_for_csv(item, f"{parent_key}{sep}{i}", sep))
        
        return items